name: Test

on: 
  push:
    tags:
    - '*'
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Download Windows
      uses: actions/download-artifact@v4
      with:
        name: windows-msix-pack
        github-token: ${{secrets.TOKEN}}
        repository: 269442033/Division2BuildTool
        run-id: 9724225679
        # path: division2buildtool.github.io 
    
    - run: |
       ls -R 
    - name: Release
      uses: softprops/action-gh-release@v2